[project]
name = "linear regression"
version = "0.1.0"
description = "Fits data"
readme = "README.md"
authors = [
    { name = "marwan404", email = "marwanabdelmajeed29@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
]

[project.scripts]
price-predictor = "price_predictor:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
